### PR TITLE
feat: targeting campaigns by post type

### LINKED ISSUE #567: Target campaigns by post type
Some plugins (such as [Newspack Podcasts](https://github.com/Automattic/newspack-podcasts)\) register their own CPTs. Customers should be able to target campaigns to specific post types such as these.

The current workaround is to apply a dedicated category or tag to each CPT and then target a campaign using those terms.

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #567 .

### How to test the changes in this Pull Request:

1. Create a prompt, observe a new panel in the sidebar editor - "Post Types"
2. Observe "Posts" and "Pages" selected by default
3. Publish the prompt, observe it behaving as expected
4. Visit a CPT, observe the prompt is not visible there
5. In the editor select the CPT name and re-publish the prompt
6. Observe the prompt visible on the respective CPT
7. Create another prompt, and use a filter to set globally supported CPTs*
8. Publish the prompt, observe it is visible on the globally-enabled CPT

\* e.g.:  
```
add_filter( 'newspack_campaigns_post_types_for_campaigns', function( $post_types ) {
	$post_types[] = 'press_release';
	return $post_types;
} );
```

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — APPROVED** [review]
Working nicely! Non-blocking suggestion: if globally enabled post types display a campaign regardless of the campaign selected post types, I think it would be best if it's hidden or displayed as a checked and disabled option with a `(global)` hint.

**Comment by adekbadek** [comment]
> if globally enabled post types display a campaign regardless of the campaign selected post types, I think it would be best if it's hidden or displayed as a checked and disabled option with a (global) hint.

It's the other way around - prompt's setting override global settings. See [this test](https://github.com/Automattic/newspack-popups/pull/607/files#diff-4319183049308ab34d8928f497fcbcfe9916dbe6e9fa19fa4aea5a81db7c1f22R114-R127) - globally the prompts are set to display on `press-release` CPT, but the prompt is set to display only on `podcast` CPT. "Global" here is not the override, it's [the default](https://github.com/Automattic/newspack-popups/pull/607/files#diff-b5dd86616b863a996219f2509687040e7092b107f3e6c9ce9e6ad859b8321874R371) for new prompts.

**Comment by miguelpeixe** [comment]
Of course! Thank you for clarifying. That leads me to another question though, if a campaign is set to `post` and `page` by default, when will it use the globally enabled post types?

**Comment by adekbadek** [comment]
> if a campaign is set to post and page by default, when will it use the globally enabled post types?

It will use the globally enabled post types unless the supported post types have been changed for this specific prompt. See example in [this part of the tests](https://github.com/Automattic/newspack-popups/pull/607/files#diff-4319183049308ab34d8928f497fcbcfe9916dbe6e9fa19fa4aea5a81db7c1f22R39-R46).

**Pull request merged**
