### PR TITLE
Campaigns Wizard: mark draft prompts in preview

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

When previewing, a user might be confused as to what will actually be visible for the reader. In this PR, styling for inactive (draft) prompts is introduced in the preview window.

### How to test the changes in this Pull Request:

1. Visit the Campaigns Wizard
2. Preview a segment
3. Observe that inactive (draft) prompts are marked with striped overlay and a label in top-left corner

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
@adekbadek in https://github.com/Automattic/newspack-popups/pull/435/commits/5410750cb61eec171a202439f576aadda1cdfe83 I made some adjustments

* I removed the stripped background because it felt too distracting and it would be hard for a user to have a real sense of what the prompt would be like on their website.
* The "inactive" label is now in black and white with system font to increase readability.

Should "inactive" be translatable?

**Review by dkoo — CHANGES_REQUESTED** [review]
I agree that the "Inactive" label should be translatable. I also wonder if it should be more descriptive of the actual post status? e.g. "Draft", "Pending Review" or "Scheduled"

**Comment by adekbadek** [comment]
Updated to show the actual (non-published) status.

**Review by thomasguillot — APPROVED** [review]

**Review by dkoo — APPROVED** [review]
Looks great!

**Pull request merged**
