### PR TITLE
Improve preview post link

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [X] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a password check to preview post getting. 

### How to test the changes in this Pull Request:

1. Make the most recent post password-protected
2. On `master`, observe that the campaign preview will use homepage for previews
3. Switch to this branch, observe that the campaign preview will use the most recent not-password-protected post

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by jeffersonrabb — CHANGES_REQUESTED** [review]
I'm having trouble reproducing the error. 

- Created a new post, turned on password protection, published.
- Edited an overlay campaign and previewed. The preview was in the password-protected post.
- Tried the same for an inline campaign, same result.
- In the Newspack Campaigns Wizard, the password protected post is used for the inline campaign BUT the home is used for the overlay. 

Is this expected behavior?

**Comment by adekbadek** [comment]
> Edited an overlay campaign and previewed. The preview was in the password-protected post.

That's not how it should be, and different than on my machine. It's odd since the WP query parameter is pretty simple:
https://github.com/Automattic/newspack-popups/pull/291/files#diff-c7efd1b032b601286ed42b644beb0443eaa33ce019c42dc068c443adaf1028fdR256

> In the Newspack Campaigns Wizard, the password protected post is used for the inline campaign BUT the home is used for the overlay. Any idea what might be wrong with the WP query here?

This is expected unless `newspack-popups` is on this PR's branch and `newspack-plugin` is on https://github.com/Automattic/newspack-plugin/pull/690 's branch

**Review by dkoo — APPROVED** [review]
This worked for me—created a password-protected post, edited both inline and overlay campaigns, the preview shown for both was the next (non-password-protected) post.

**Review by jeffersonrabb — APPROVED** [review]
Tried again, worked this time. I must have done something wrong the first time.

**Pull request merged**
