### PR TITLE
Release May 07

### PR DESCRIPTION
**Pull request by adekbadek**
A new release.

### CODE REVIEW

**Review by chickenn00dle — DISMISSED** [review]

**Comment by claudiulodro** [comment]
Note: this release doesn't have any useful changes, so not tagging.

**Comment by adekbadek** [comment]
It does contain one `fix`: https://github.com/Automattic/newspack-popups/pull/1296

**Comment by dkoo** [comment]
Ah, I missed that. Sorry! Will merge now

**Comment by dkoo** [comment]
Wait, actually—#1296 was already released in [v2.31.2](https://github.com/Automattic/newspack-popups/releases/tag/v2.31.2). The changelog in this PR is showing a bunch of changes from prior hotfixes. The actual changeset does not contain any new fixes or features:

Screenshot 2024-05-16 at 9 29 53 AM

**Pull request closed without merging**
