### PR TITLE
Add posts read count segmentation

### LINKED ISSUE #271: Segmentation: read posts count
Segmentation based on read posts count.

---

_This issues was originally about Segmentation UI, but the UI has to do something. The read posts count seemed like a good candidate for the first functionality of this UI._

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #271.

### How to test the changes in this Pull Request:

1. In `newspack-plugin`, switch to `add/segmentation-ui` branch
2. Observe a new tab in the Campaigns wizard – "Segmentation"
3. Create a segment with minimum read articles count of 3 and maximum of 5
4. Create a campaign, observe a new select in the sidebar – "Segment"
5. Choose the newly created segment and publish the campaign
6. Observe that the campaign is shown only when reading the 3rd, 4th, and 5th article
7. Experiment a bit more with segments (e.g. remove a segment after a campaign was assigned one, try different configurations of min. and max. articles read count)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by jeffersonrabb — CHANGES_REQUESTED** [review]
After initially adding the segment in Campaigns Wizard I get a white screen with these console errors:

```
Uncaught TypeError: Cannot read property 'format' of undefined
    at SegmentActionCard (SegmentsList.js:72)
    at renderWithHooks (react-dom.js?ver=16.9.0:15246)
    at mountIndeterminateComponent (react-dom.js?ver=16.9.0:17480)
    at beginWork$1 (react-dom.js?ver=16.9.0:18624)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.9.0:341)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.9.0:391)
    at invokeGuardedCallback (react-dom.js?ver=16.9.0:448)
    at beginWork$$1 (react-dom.js?ver=16.9.0:23355)
    at performUnitOfWork (react-dom.js?ver=16.9.0:22349)
    at workLoopSync (react-dom.js?ver=16.9.0:22323)
react-dom.js?ver=16.9.0:19952 The above error occurred in the <SegmentActionCard> component:
    in SegmentActionCard (created by SegmentsList)
    in div (created by SegmentsList)
    in div (created by SegmentsList)
    in SegmentsList (created by PopupSegmentation)
    in PopupSegmentation (created by WrappedWithWizardScreen)
    in div (created by Card)
    in Card (created by WrappedWithWizardScreen)
    in div (created by Grid)
    in Grid (created by WrappedWithWizardScreen)
    in WrappedWithWizardScreen (created by Context.Consumer)
    in Route (created by WebPreview)
    in Switch (created by WebPreview)
    in Router (created by HashRouter)
    in HashRouter (created by WebPreview)
    in WebPreview (created by PopupsWizard)
    in PopupsWizard (created by WrappedWithWizard)
    in div (created by WrappedWithWizard)
    in WrappedWithWizard

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.js?ver=16.9.0:19952
SegmentsList.js:72 Uncaught (in promise) TypeError: Cannot read property 'format' of undefined
    at SegmentActionCard (SegmentsList.js:72)
    at renderWithHooks (react-dom.js?ver=16.9.0:15246)
    at mountIndeterminateComponent (react-dom.js?ver=16.9.0:17480)
    at beginWork$1 (react-dom.js?ver=16.9.0:18624)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.9.0:341)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.9.0:391)
    at invokeGuardedCallback (react-dom.js?ver=16.9.0:448)
    at beginWork$$1 (react-dom.js?ver=16.9.0:23355)
    at performUnitOfWork (react-dom.js?ver=16.9.0:22349)
    at workLoopSync (react-dom.js?ver=16.9.0:22323)
```

After navigating away the error occurs every time the Campaigns Wizard is loaded.

**Comment by jeffersonrabb** [comment]
Update, I mistakenly added this comment before reading @dkoo's notes in https://github.com/Automattic/newspack-plugin/pull/689. Sorry for the duplication and noise!

**Comment by adekbadek** [comment]
@jeffersonrabb The plugin part should be fixed now!

**Review by dkoo — APPROVED** [review]
This is working for me as described.

**Pull request merged**
