### PR TITLE
Handle visit data also in previews

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Enable cookie spoofing when previewing.

TODO/Question: this would spam the logs and DB with the preview-generated data – perhaps it should be removed in a CRON job?

### How to test the changes in this Pull Request:

Follow instructions in https://github.com/Automattic/newspack-plugin/pull/891

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by dkoo** [comment]
> TODO/Question: this would spam the logs and DB with the preview-generated data – perhaps it should be removed in a CRON job?

I thought about this too. Could the preview UI clean up any preview user data when the preview modal is closed? Either way we should probably not launch this feature without a solution for this, right?

**Review by dkoo — APPROVED** [review]
Approving because this works as described, but we'll need to fix conflicts with `master` and probably also answer the unresolved question about DB and log cleanup before we merge this.

**Comment by adekbadek** [comment]
Proposed solution to the preview data logging issue: disregard it when fetching all clients data (used in computing the potential segment reach). This should suffice, since this is the only case when preview data can manifest itself as noise, and we just store last 30 days worth of data anyway.

**Review by dkoo — APPROVED** [review]
> Proposed solution to the preview data logging issue: disregard it when fetching all clients data (used in computing the potential segment reach). This should suffice, since this is the only case when preview data can manifest itself as noise, and we just store last 30 days worth of data anyway.

Oh, this is a great solution. Thanks for implementing! Let's get this merged.

**Pull request merged**
