### PR TITLE
Overlay Improvements

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The Overlay is now clickable/dismiss-able in addition to the close button. Clicking the overlay behind the pop-up should have exactly the same  effect as clicking the close button - the popup is dismissed, and the `newspack-popups/v1/reader` API is called. There is also an overlay opacity range control, which can be set from 0-100.

Screen Shot 2019-11-06 at 6 46 19 PM

cc: @tristanloper 

### How to test the changes in this Pull Request:

1. Create a pop-up with Frequency=Every Page View, Trigger=Scroll Progress, Scroll Progress=20. 
2. View the site in an incognito window, and navigate to any single post. The popup should appear as you scroll down.
3. Click the background and verify the Pop-up is dismissed.
4. Alter the overlay opacity setting, and verify the change.
5. Change the Frequency to "Once A Day."
6. View a post, the popup should appear. Click the overlay to dismiss.
7. View another post, the popup should not appear (demonstrating that the  API call was made when the overlay was clicked.)
8. Verify the close button continues to work as before.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
How about adding an "Overlay Color" setting?

Screenshot 2019-11-07 at 08 41 50

**Comment by jeffersonrabb** [comment]
> How about adding an "Overlay Color" setting?

Good idea. Done in https://github.com/Automattic/newspack-popups/pull/17/commits/ac123a96bfd064a3c88389308456a15b8eca5eb8

Screen Shot 2019-11-07 at 8 14 13 AM

**Comment by thomasguillot** [comment]
> Good idea. Done in [ac123a9](https://github.com/Automattic/newspack-popups/commit/ac123a96bfd064a3c88389308456a15b8eca5eb8)

This is amazing!

**Comment by jeffersonrabb** [comment]
@thomasguillot we're starting to have a lot of options in that sidebar, all combined in Pop-up Settings. Do you think we should explore multiple panels with subsets of fields?

**Comment by thomasguillot** [comment]
@jeffersonrabb Yeah, maybe we should separate the Overlay.

**Comment by jeffersonrabb** [comment]
> Yeah, maybe we should separate the Overlay.

Since we have numerous open PRs that add different settings, how about we assess after they all 🚢 ?

**Comment by thomasguillot** [comment]
> Since we have numerous open PRs that add different settings, how about we assess after they all 🚢 ?

Sounds good. 👍

**Pull request merged**
