### PR TITLE
Update text in settings section

### PR DESCRIPTION
**Pull request by yogeshbeniwal**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Update text in settings section to describe current behaviour of plugin as per [documentation](https://newspack.pub/support/campaigns/settings/)

- Permanently dismisssed rather than dismissed

### How to test the changes in this Pull Request:

1. Check out this branch
2. Make sure that updated text is reflected in settings section

Description: Suppress newsletter prompts if permanently dismissed
Help: Automatically suppress any dismissible prompt that contains a newsletter signup block if at least one prompt with a signup block has been permanently dismissed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by dkoo** [comment]
@yogeshbeniwal Is this update still needed after #832 has been merged? If so, please update the PR and I'll take another look.

**Comment by yogeshbeniwal** [comment]
@dkoo Yes, I think so. Wording in latest version still says "Suppress newsletter prompts if dismissed
Automatically suppress any dismissible prompt that contains a newsletter signup block if at least one prompt with a signup block has been dismissed." vs what what is proposed above mentioning **permanent** dismissal

**Comment by dkoo** [comment]
@yogeshbeniwal sounds fine to me—looks like you need to rebase your branch and/or fix some conflicts with `master`. Once that's resolved I'll approve.

**Comment by yogeshbeniwal** [comment]
@dkoo Done in [bbdcb24](https://github.com/Automattic/newspack-popups/pull/834/commits/bbdcb2470bfd16154149f65e5ce1d411f1577fdf)

**Review by dkoo — APPROVED** [review]
Thanks for the contribution, @yogeshbeniwal!

**Pull request merged**
