### PR TITLE
Add an alignment/placement setting

### LINKED ISSUE #8: Add an alignment option to the popup
In order to introduce some more flexibility, I suggest we add an alignment option to the settings.

We could use the `components-toolbar` to achieve this:

Screenshot 2019-10-30 at 10 24 52

__Front end:__

1 center
2 bottom
3 top
4 left
5 right

__Icons:__
https://cloudup.com/cPxISuzUkpx

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add an option to the pop-up in order to align it:
* Center
* Bottom
* Top
* Left
* Right

Screenshot 2019-10-31 at 11 54 32
1 center
2 bottom
3 top
4 left
5 right

Closes #8.

### How to test the changes in this Pull Request:

1. Switch to this branch and run `npm run build`
2. Edit a Pop-up and open the popup settings 
3. Play with the different alignments and check the front-end.
4. Resize your screen (height and width). Can you still access the content of the pop-up.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
The width of the centered popup feels small in this screenshot. Is this the intended size?

Screen Shot 2019-10-31 at 8 28 43 AM

**Comment by jeffersonrabb** [comment]
For top/bottom placement, what would you think about animating them vertical so they slide in from the top or bottom?

**Comment by jeffersonrabb** [comment]
I'm skeptical of the left/right placements. I could be mistaken but I don't think I've ever seen this approach in the wild. A popup with typical form content like the Donate or Mailchimp block ends up with a great deal of white space at the bottom:

Screen Shot 2019-10-31 at 8 54 54 AM

On mobile the popup fills the entire viewport (unlike centered, top, or bottom placements):

Screen Shot 2019-10-31 at 8 56 29 AM

**Comment by thomasguillot** [comment]
> The width of the centered popup feels small in this screenshot. Is this the intended size?

Should be fixed in cee7f74

**Comment by thomasguillot** [comment]
> For top/bottom placement, what would you think about animating them vertical so they slide in from the top or bottom?

I added some animations in fa77d63
What do you think @jeffersonrabb?

**Pull request merged**
