### PR TITLE
feat(analytics): add segment name to event_category

### LINKED ISSUE #679: Add segment name to Newspack Announcement events
Asana: https://app.asana.com/0/1200942827698993/1201001433518035
Details: https://docs.google.com/document/d/18dBs-2PiYre8msDaZswRdciSmqExVfMrN9GgpaO9qsg/edit#heading=h.88b3ppvknsme

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Makes two analytics-related changes:

1. !Changes the `event_category` label from `Newspack Announcement` to `Newspack Prompt` (@Automattic/newspack this is a potentially breaking change for sites running reports on `Newspack Announcement`—what are our collective thoughts on this?)~ Reverted this—see discussion below.
2. Adds a semicolon-delimited list of the prompt's segment(s) to each ~`event_category`~ event label, or "Everyone" if the prompt has no assigned segments

Closes #679.

### How to test the changes in this Pull Request:

1. Check out this branch and publish several prompts assigned to one, more than one, and zero segments.
3. In a new incognito window, view the page source and confirm that the analytics config now indicates the segments (or "Everyone").

Screen Shot 2022-03-21 at 5 00 01 PM

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by yogeshbeniwal** [comment]
Generally should be ok as its not affecting NTG events for newsletter signup and impression. However it will require to configure multiple graphs now in Studio, instead of one graph earlier using Event Category name. Consider adding segment name to Event Label instead.

**Comment by adekbadek** [comment]
> Changes the event_category label from Newspack Announcement to Newspack Prompt […] this is a potentially breaking change for sites running reports on `Newspack Announcement`

There might be many dashboards & reports out there relying on that category name. I'd be wary of changing this.

>  Consider adding segment name to Event Label instead.

I side with this suggestion – category should encompass all Campaings-related events, and label should contain additional data.
Note that this would probably require changes in how Newspack Plugin parses the Analytics data for display in the wizard.

**Comment by dkoo** [comment]
9c429a6 restores the "Newspack Announcement" category name (albeit keeping the translation, just in case it's needed in the future) and moves the segments to the Event Label, as suggested.

**Review by aschweigert — APPROVED** [review]
looks good to me!

**Review by miguelpeixe — APPROVED** [review]
I also agree with the suggested approach. Working as described!

**Pull request merged**
