### PR TITLE
Fix/Use WordPress Constants

### LINKED ISSUE #612: wp-content directory is hard coded,  not working with custom directories
wp-content directory is hard code at couple of places, this leads to missing config file while using custom wp-content directory

https://github.com/Automattic/newspack-popups/blob/91b056bfa7ea51ffffe9bd7312a395edb8de5be5/api/setup.php#L9

https://github.com/Automattic/newspack-popups/blob/91b056bfa7ea51ffffe9bd7312a395edb8de5be5/api/setup.php#L26

### PR DESCRIPTION
**Pull request by yogeshbeniwal**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Use WordPress constants to cover scenario where custom wp-content directory name is used

Closes #612

### How to test the changes in this Pull Request:

1. Configure WordPress to use custom WP_CONTENT_DIR
2. Apply changes proposed in this PR
3. Review access.log  for 200 Ok or Response in Developer tools.

### Other information:

- Code to be written to use wp constant for wp-content/plugins/ in  
https://github.com/Automattic/newspack-popups/blob/bb5b1cb871ca8b7f9f4c99f918c6892b49658f3b/api/setup.php#L9

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — CHANGES_REQUESTED** [review]
Thank you for contributing, @yogeshbeniwal !
This changes the value of `$config_path` from `wp-content/newspack-popups-config.php` to `wp-content/plugins/newspack-popups-config.php`, which does not seem intended.

**Comment by yogeshbeniwal** [comment]
@adekbadek Updated to use WP_CONTENT_DIR.

**Review by adekbadek — APPROVED** [review]
🙌

**Comment by yogeshbeniwal** [comment]
@adekbadek There is another line a which wp-content/plugin path is hard coded. Will leave that to your's awesome coding skills.

https://github.com/Automattic/newspack-popups/blob/bb5b1cb871ca8b7f9f4c99f918c6892b49658f3b/api/setup.php#L9

**Pull request merged**
