### PR TITLE
fix: ensure inline posts are inserted into main post content only

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

There's a weakness in the [`the_content`](https://developer.wordpress.org/reference/hooks/the_content/) filter hook in that it doesn't tell you what post object the filtered content is coming from. For this reason, the callback to insert inline prompts in article content sometimes gets called on the wrong content, as was discovered in https://github.com/Automattic/newspack-theme/pull/2127.

This PR attempts to mitigate that situation by comparing the `post_content` property on the post in the global `$wp_query` and comparing it to the `$content` string being filtered, before executing the prompt insertion logic. Since this filter callback is being called with priority `1`, before most or all other content filters would be run to transform this content string, the strings should match. I haven't done an exhaustive test of this, though.

### How to test the changes in this Pull Request:

There shouldn't be any major changes in functionality. Inline prompts should be inserted in article post content only.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
I'm not sure this is the safest strategy to mitigate the problem. If anything filters the content at priority 1 we will not have prompts rendering.

WDYT of making the filter run only once so any other run inside the content or afterward should be skipped. Does that make sense? Or does an inner run execute before the post run? 🤔

**Comment by dkoo** [comment]
> I'm not sure this is the safest strategy to mitigate the problem. If anything filters the content at priority 1 we will not have prompts rendering.

> WDYT of making the filter run only once so any other run inside the content or afterward should be skipped. Does that make sense? Or does an inner run execute before the post run? 🤔

We already run the filter only once, but unfortunately in the bug found in https://github.com/Automattic/newspack-theme/pull/2127 the featured image caption filter runs before the post content. 😞

**Review by miguelpeixe — APPROVED** [review]
Ah, I didn't realize that :(

Well, it tests well!

**Comment by dkoo** [comment]
I always wish the `the_content` filter hook would provide a post ID as a second arg, but alas.

If this causes future issues we could try a less-precise comparison, such as stripping all tags and comparing the first 50 characters, or something similar...

**Pull request merged**
