### PR TITLE
Fix time-triggered popups edge case

### LINKED ISSUE #241: Time-triggered campaigns will not show properly if page is loaded with scroll offset
A time-triggered campaign is still scroll-triggered, but the position observer is at the top of content, which makes this work only if page is loaded with scroll offset of 0 (most cases).

## How to reproduce

1. Create a time-triggered test campaign
2. Visit a page, observe the campaign is shown, as it should, after the delay
3. Scroll to the bottom of the page, reload
4. Observe the campaign is not shown after the delay, but only after scrolling to top, and then after the delay

### LINKED ISSUE #247: Test Mode Not Working On Non-AMP Pages
Campaigns in Test Mode do appear correctly in non-AMP logged in pages. They do work correctly in AMP pages.

Steps to reproduce:

1) Put AMP plugin in Transitional mode.
2) Create an overlay Campaign in Test mode.
3) View any Post while still logged in. Observe the Campaign does not appear.
4) Switch to AMP version of page, observe the Campaign appears correctly.
5) Change the Campaign to Inline and re-try steps 3 and 4. In the non-AMP page the Campaign does appear, but the borders are broken as shown in this screenshot:

Screen Shot 2020-10-18 at 10 57 48 PM

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In some cases, time-triggered popups will not show until scrolling.

Closes #241 
Closes #247

### How to test the changes in this Pull Request:

1. Create a time-triggered popup, set to test mode
1. On `master`, visit the site, scroll to the bottom, and reload
2. Observe the popup is not shown until site is scrolled to top
3. Switch to this branch
4. Observe the popup is displayed when loading the page with scroll offset

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
It's possible that this is due to a bad merge on my part (I tried to merge the latest from master in before testing), but this is the behavior I see on this branch:

- [x] The time-triggered overlay appeared correctly after the delay, without having to scroll (as expected).
- [ ] Without dismissing the modal, after refreshing the page, the overlay did not appear again, even after scrolling back to the top of the page (I would expect that it should appear since I didn't click the "I'm not interested" link)

I'll re-test and re-review after this branch is updated with changes from master.

**Comment by adekbadek** [comment]
@dkoo I've merged in master and fixed a bug which prevented test popups being displayed. This would not be the reason for the issue reported in your comment, though.

**Comment by adekbadek** [comment]
Update: This closes #247

**Review by jeffersonrabb — APPROVED** [review]
🚢

**Comment by dkoo** [comment]
@adekbadek Behavior looks good to me. In test mode on both AMP and non-AMP pages, the time-triggered overlay appears on both initial page load and subsequent reloads both with and without a scroll offset. 👍

**Review by dkoo — APPROVED** [review]

**Pull request merged**
