### PR TITLE
Filter out non-existing categories in segments

### LINKED ISSUE #491: Segmentation - handle removed categories
## To reproduce:

1. Create a segment, set "Category Affinity" to a category
2. Remove that category from WordPress instance
3. Edit the segment, observe that there's nothing in the "Category Affinity" input, but "Has favorite categories" still appears in segment description in segments list
4. Note that any prompts assigned to this category will never be shown

## Proposed solution:

The non-existent categories should be filtered out from segment.

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #491.

### How to test the changes in this Pull Request:

Observe that #491 is not reproducible 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
In my experience, if the category you delete is the only category applied to a prompt, that prompt will inherit the default ("Uncategorized" on my site) category. Can we check for the default category and remove it in this case?

**Comment by adekbadek** [comment]
That's a different scenario - this PR deals with assigning categories to a segment, not to a prompt.
Removing the default category application was handled in #482 - please open an issue if that does not work as expected.

**Comment by dkoo** [comment]
Got it, let me re-test with that in mind.

**Review by dkoo — APPROVED** [review]
This works as expected for segments (created a new issue #530 for what I mentioned above). 

Non-blocking question, though: if a segment's only criteria is the deleted category, after deleting the category the segment effectively becomes "empty", which means it will behave the same as "Everyone" (prompts in the segment will be shown to all readers). 

The segmentation UI already tries to prevent admins from creating empty segments, so this becomes a backdoor way of doing just that. Is this something we should be concerned about or at least notify users about?

**Comment by adekbadek** [comment]
> The segmentation UI already tries to prevent admins from creating empty segments, so this becomes a backdoor way of doing just that. Is this something we should be concerned about or at least notify users about?

I think this is very much an edge case. If a segment targets a specific category, it's probably an important one (and so not prone to accidental removal).

**Pull request merged**
