### PR TITLE
fix: install composer dependencies on release job

### LINKED ISSUE #359: Releases Don't Include Vendor Directory
Releases of the plugin made using the CI automated release workflow don't include the vendor directory. This leads to this fatal on production sites:

```
PHP Fatal error: require_once(): Failed opening required '/wordpress/plugins/newspack-popups/1.21.0/api/segmentation/../../vendor/autoload.php' (include_path='/:.') in /wordpress/plugins/newspack-popups/1.21.0/api/segmentation/class-segmentation-client-data.php on line 13
```

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Includes composer dependencies in the release job, otherwise the segmentation API won't work. 

Closes #359.

### How to test the changes in this Pull Request:

1. Create an alpha release by merging this branch into the `alpha` branch.
2. In CircleCI, confirm that the alpha release job completes successfully without errors.
3. Install the alpha release package on a test site, confirm that all segmentation features are working as expected.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
After creating a `fix/release-error`->`alpha` merge [here](https://github.com/Automattic/newspack-popups/pull/369), the automated build [failed](https://app.circleci.com/pipelines/github/Automattic/newspack-popups/788/workflows/ddaf22c8-fb7d-433c-8066-f30acc7e4ee4/jobs/2465) with this message:

```
#!/bin/bash -eo pipefail
composer install --no-dev --no-scripts
/bin/bash: composer: command not found

Exited with code exit status 127
CircleCI received exit code 127
```

**Review by jeffersonrabb — CHANGES_REQUESTED** [review]
After creating a `fix/release-error`->`alpha` merge [here](https://github.com/Automattic/newspack-popups/pull/369), the automated build [failed](https://app.circleci.com/pipelines/github/Automattic/newspack-popups/788/workflows/ddaf22c8-fb7d-433c-8066-f30acc7e4ee4/jobs/2465) with this message:

```
#!/bin/bash -eo pipefail
composer install --no-dev --no-scripts
/bin/bash: composer: command not found

Exited with code exit status 127
CircleCI received exit code 127
```

**Comment by dkoo** [comment]
@jeffersonrabb Looks like I had to pull in some additional config changes from the plugin config to get this to work. Should be working now: https://app.circleci.com/pipelines/github/Automattic/newspack-popups/790/workflows/4a0b4cc3-f6cd-473c-8a78-43399af17a76

**Review by adekbadek — APPROVED** [review]

**Review by jeffersonrabb — APPROVED** [review]
Tested again, and it appears to have worked. 

PR: https://github.com/Automattic/newspack-popups/pull/384
Release: https://github.com/Automattic/newspack-popups/releases/tag/v1.2.0-alpha.1

**Pull request merged**
