### PR TITLE
Fix tag filtering

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes a bug

### How to test the changes in this Pull Request:

1. On `master`, create a prompt and set a tag on it
2. Visit a post with no tags, observe that the prompt is displayed anyway
3. Switch to this branch, observe the prompt is not displayed

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — APPROVED** [review]
Nice, this works now. This begs the question, though, should we include a Tag Filtering field in the quick menu? Right now it's not obvious in the UI that you can filter by tags as well as by categories (hence why I thought we didn't support it initially).

Screen Shot 2021-03-31 at 12 11 22 PM

**Comment by adekbadek** [comment]
Hm, I worry the UI might become cluttered. WDYT @thomasguillot ?

**Comment by thomasguillot** [comment]
> I worry the UI might become cluttered

Yes, absolutely. Maybe the Category and Tag filters could have to their own menu?

**Comment by adekbadek** [comment]
A third button (with a filter icon), here?

image

It could contain segment, category, and tags, as these are all filtering options.

**Comment by thomasguillot** [comment]
Yeah, possibly.

**Comment by dkoo** [comment]
> A third button (with a filter icon), here?

Probably a task for another PR, right? I created an issue for it here: https://github.com/Automattic/newspack-plugin/issues/926

So we can go ahead and merge this PR since it fixes the tag filtering functionality.

**Comment by adekbadek** [comment]
Thanks for the issue - this branch has already been merged :)

**Pull request merged**
