### PR TITLE
Add above header placement option

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [X] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds an "above header" campaign placement, as requested in #260

Additional changes in Theme (https://github.com/Automattic/newspack-theme/pull/1131) and the plugin (https://github.com/Automattic/newspack-plugin/pull/691)

### How to test the changes in this Pull Request:

1. Create a new campaign, observe a new option in "Placement" select – "Above site header"
2. Use this option
3. Verify that the campaign is placed above site header
4. Filtering (category, tag, etc.) and everything else should work as with a regular inline campaign

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
I happened to notice while testing #1131 that the above header popup seems to appear twice on pages like the search results and archives, once above the header and once below: 

image

I haven't tested extensively, but the above is in test mode and appears with and without AMP enabled; it displays only once on single posts and pages.

**Review by dkoo — CHANGES_REQUESTED** [review]
Looks like the `before_header` hook is firing twice on category archive pages, resulting in the "above header" campaigns appearing 2x each.

**Comment by dkoo** [comment]
Another weird thing I noticed is that when not logged in, I'm seeing extra `<br>` tags being added inside certain label/button elements in the Homepage Posts block. I haven't figured out where they're coming from, but it only happens when this branch is active.

**Comment by adekbadek** [comment]
> the above header popup seems to appear twice on pages like the search results and archives

Thanks for catching that, should be fixed by 2d0ede60d0e41e6546a94c0855981262f66f34fd 👍

**Comment by adekbadek** [comment]
> Another weird thing I noticed is that when not logged in, I'm seeing extra <br> tags being added inside certain label/button elements in the Homepage Posts block.

Whoa, that's a good catch! Looks like re-building the post content without any campaigns caused this issues. Fixed in 35ff3ac66099443468886242c83628d5b7582ade

**Review by dkoo — APPROVED** [review]
Looks good to me now!

**Comment by adekbadek** [comment]
So now this waits for theme changes – https://github.com/Automattic/newspack-theme/pull/1131

**Comment by adekbadek** [comment]
(Should be release in tandem with https://github.com/Automattic/newspack-plugin/pull/691, awaiting review there)

**Review by dkoo — APPROVED** [review]

**Pull request merged**
