### PR TITLE
Pop-up Background Color Control

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a background color picker for Pop-ups, with a default of white.

Closes https://github.com/Automattic/newspack-popups/issues/49

Screen Shot 2020-02-03 at 12 42 34 AM

Screen Shot 2020-02-03 at 12 42 48 AM

### Design Questions:

- Will this feature make it too easy to produce unattractive Pop-ups? Should there be any restrictions on it?
- There is a border around Pop-up that I'm having trouble tracking down. Is this problematic? 
- I moved the background color from `newspack-popup` to `newspack-popup-wrapper`. Any issue with this?

### How to test the changes in this Pull Request:

1. Create a Pop-up, Trigger=Timer, Delay=1, Frequency=Test Mode, Placement=Center. Leave Background Image untouched.
2. Open site homepage, verify the Pop-up appears and looks exactly like it did previously.
3. Edit the Pop-up and set a background color. 
4. Open homepage again, verify Pop-up appears with correctly colored background.
5. Try all Placement options.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
> We need to add some sort of contrast checker otherwise the content can be unreadable if the user picks a dark background colour.
> 
> It'd also be interesting to see the backgound colour in the editor.

Both are done in https://github.com/Automattic/newspack-popups/pull/52/commits/2c84f8d5e5b4d49d75d8edb3d086649599f9de4d and https://github.com/Automattic/newspack-popups/pull/52/commits/22d9ca6dc6adf4d4fc66db0bd4298792f73d3938.

**Comment by jeffersonrabb** [comment]
Rebased.

**Comment by thomasguillot** [comment]
> In this example, the contrast ratio is 1.24 (#9CFF5E vs #FFFFFF) and it should be using black, not white.

_Note: front-end seems fine_

**Comment by jeffersonrabb** [comment]
> Note: front-end seems fine

OK, so we're seeing inconsistencies between the PHP and Javascript implementations of the contrast logic.

**Comment by jeffersonrabb** [comment]
> I'm not quite sure how the contrast checker works though.

Should be fixed in https://github.com/Automattic/newspack-popups/pull/52/commits/0e33631972d44cbfca9af7a2a592692e5570bbd9.

**Comment by jeffersonrabb** [comment]
A fair amount has changed in this one, so I re-requested @adekbadek's review.

**Comment by jeffersonrabb** [comment]
> Or they are both bugs and should both have no value after saving since it was unchecked

I think they are both bugs. I'm going to file and try to fix both together in a separate PR.

**Pull request merged**
